name: "Create release-notes.md"
author: tomozo6
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        TAG_LATEST=$(git tag -l --sort=-v:refname | head -n 1)
        echo "TAG_LATEST=${TAG_LATEST}"
        TAG_PREVIOUS=$(git tag -l --sort=-v:refname | head -n 2 | tail -n 1)
        echo "TAG_PREVIOUS=${TAG_PREVIOUS}"
        echo "## What's Changed" > release-notes.md
        git log --oneline --decorate=no ${TAG_PREVIOUS}..${TAG_LATEST} | while read LINE ; do echo "- ${LINE}" >> release-notes.md ; done