name: Release

on:
  push:
    tags:
      - "*"

jobs:
  ecr-push:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Setup Variables
        id: variables
        run: echo "::set-output name=tagversion::${GITHUB_REF}"

      - name: Use TagVariables
        run: echo ${{ steps.variables.outputs.tagversion }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Git Messages
        id: variables
        run: |
          GIT_TAG_LATEST=$(git tag -l --sort=-v:refname | head -n 1)
          echo "GIT_TAG_LATEST=${GIT_TAG_LATEST}" >> $GITHUB_ENV
          GIT_TAG_LATEST_BEFORE_ONE=$(git tag -l --sort=-v:refname | head -n 2 | tail -n 1)
          echo "GIT_TAG_LATEST_BEFORE_ONE=${GIT_TAG_LATEST_BEFORE_ONE}" >> $GITHUB_ENV
          GIT_MSGS=$(git log --oneline --decorate=no ${GIT_TAG_LATEST_BEFORE_ONE}..${GIT_TAG_LATEST})
          echo "::set-output name=GIT_MSGS::${GIT_MSGS}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.variables.outputs.GIT_MSGS }}
          draft: false
          prerelease: false