name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  ecr-push:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Setup TagVariables
        id: variables
        run: echo "::set-output name=tagversion::${GITHUB_REF}"

      - name: Use TagVariables
        run: echo ${{ steps.variables.outputs.tagversion }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Git Messages
        run: |
          GIT_MSGS=$(git log --oneline --decorate=no)
          echo "${GIT_MSGS}"
          GIT_TAG_LATEST=$(git tag -l --sort=-v:refname | head -n 1)
          echo "${GIT_TAG_LATEST}"
          GIT_TAG_LATEST_BEFORE_ONE=$(git tag -l --sort=-v:refname | head -n 2 | tail -n 1)
          echo "${GIT_TAG_LATEST_BEFORE_ONE}"


