name: Release

on:
  push:
    tags:
      - "*"

jobs:
  ecr-push:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Release Notes
        uses: tomozo6/create-release-notes@main
        id: create-release-notes

      - shell: bash
        run: |
          echo ${{ steps.create-release-notes.outputs.RELEASE_NOTES }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name:  ${{ github.ref }}
          body: |
            ${{ steps.create-release-notes.outputs.RELEASE_NOTES }}
          draft: false
          prerelease: false
