name: Release

on:
  push:
    tags:
      - "*"

jobs:
  ecr-push:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Setup Variables
        id: variables
        run: echo "::set-output name=tagversion::${GITHUB_REF}"

      - name: Use TagVariables
        run: echo ${{ steps.variables.outputs.tagversion }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create release-notes.md
        uses: tomozo6/create-release-notes@main

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name:  ${{ github.ref }}
          body_path: release-notes.md
          draft: false
          prerelease: false
